name = "GeneticVariantBase"
uuid = "2447270c-d849-4bf9-ac0d-b5c0b265991c"
authors = ["Seyoon Ko <kos@ucla.edu> and contributors"]
version = "0.1.2"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
